/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Login.usuarios;

/**
 *
 * @author Victor Olave
 */
public class Home extends javax.swing.JFrame {
    
    usuarios mod;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
    }
    
    public Home(usuarios mod)
    {
        initComponents();
        this.mod = mod;
        
        lblnombre.setText(mod.getNombre());
        lbltipo.setText(mod.getNombre_tipo());
        
        if(mod.getId_tipo() == 1)
        {
            
            
        }
        else if(mod.getId_tipo() == 2)
        {
             menuregistrar.setVisible(false);
             menuregistrarT.setVisible(false);
             menuregistrarP.setVisible(false);
             ctrlUsuarios.setVisible(false);
        }
        else if (mod.getId_tipo() == 3)
        {
             rempleado.setVisible(false);
             jMenuItem5.setVisible(false);
             cempleado.setVisible(false);
             consultarempleadosT.setVisible(false);
             jMenuItem9.setVisible(false);                       
             ctrlUsuarios.setVisible(false);
        }
        else if (mod.getId_tipo() == 4)
        {
             menuBuses.setVisible(false);
             menuTaxis.setVisible(false);
             menuPreferencial.setVisible(false);
             ctrlUsuarios.setVisible(false);
        }
        
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lbltipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        ctrlUsuarios = new javax.swing.JMenuItem();
        menuBuses = new javax.swing.JMenu();
        menuregistrar = new javax.swing.JMenu();
        rempleado = new javax.swing.JMenuItem();
        rvehiculo = new javax.swing.JMenuItem();
        menuconsultar = new javax.swing.JMenu();
        cempleado = new javax.swing.JMenuItem();
        cvehiculo = new javax.swing.JMenuItem();
        menuTaxis = new javax.swing.JMenu();
        menuregistrarT = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuconsultarT = new javax.swing.JMenu();
        consultarempleadosT = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuPreferencial = new javax.swing.JMenu();
        menuregistrarP = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuconsultarP = new javax.swing.JMenu();
        consultarempleadosP = new javax.swing.JMenuItem();
        consultarvehiculosP = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(350, 600));
        setMinimumSize(new java.awt.Dimension(350, 600));
        setPreferredSize(new java.awt.Dimension(350, 600));
        setSize(new java.awt.Dimension(350, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Transpipian Logo(2).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 130, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BIENVENIDO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 280, 89));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado5.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 260));

        lblnombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 169, 42));

        lbltipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lbltipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 151, 36));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo 1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 809, 540));

        jMenu10.setText("Inicio");

        ctrlUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ctrlusuarios.png"))); // NOI18N
        ctrlUsuarios.setText("Ctrl Usuarios");
        ctrlUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlUsuariosActionPerformed(evt);
            }
        });
        jMenu10.add(ctrlUsuarios);

        jMenuBar2.add(jMenu10);

        menuBuses.setText("Buses");

        menuregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro.png"))); // NOI18N
        menuregistrar.setText("Registrar");

        rempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado2.png"))); // NOI18N
        rempleado.setText("Empleado");
        rempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rempleadoActionPerformed(evt);
            }
        });
        menuregistrar.add(rempleado);

        rvehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autobu.png"))); // NOI18N
        rvehiculo.setText("Vehiculo");
        rvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rvehiculoActionPerformed(evt);
            }
        });
        menuregistrar.add(rvehiculo);

        menuBuses.add(menuregistrar);

        menuconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/binoculares.png"))); // NOI18N
        menuconsultar.setText("Consultar");

        cempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado3.png"))); // NOI18N
        cempleado.setText("Empleados");
        cempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cempleadoActionPerformed(evt);
            }
        });
        menuconsultar.add(cempleado);

        cvehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/autobu2.png"))); // NOI18N
        cvehiculo.setText("Vehiculos");
        cvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvehiculoActionPerformed(evt);
            }
        });
        menuconsultar.add(cvehiculo);

        menuBuses.add(menuconsultar);

        jMenuBar2.add(menuBuses);

        menuTaxis.setText("Taxis");

        menuregistrarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro.png"))); // NOI18N
        menuregistrarT.setText("Registrar");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado2.png"))); // NOI18N
        jMenuItem5.setText("Empleado");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuregistrarT.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/taxi2.png"))); // NOI18N
        jMenuItem6.setText("Vehiculo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuregistrarT.add(jMenuItem6);

        menuTaxis.add(menuregistrarT);

        menuconsultarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/binoculares.png"))); // NOI18N
        menuconsultarT.setText("Consultar");

        consultarempleadosT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado3.png"))); // NOI18N
        consultarempleadosT.setText("Empleados");
        consultarempleadosT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarempleadosTActionPerformed(evt);
            }
        });
        menuconsultarT.add(consultarempleadosT);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/taxi3.png"))); // NOI18N
        jMenuItem2.setText("Vehiculos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuconsultarT.add(jMenuItem2);

        menuTaxis.add(menuconsultarT);

        jMenuBar2.add(menuTaxis);

        menuPreferencial.setText("Preferencial");

        menuregistrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro.png"))); // NOI18N
        menuregistrarP.setText("Registrar");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado2.png"))); // NOI18N
        jMenuItem9.setText("Empleado");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuregistrarP.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descapotable.png"))); // NOI18N
        jMenuItem10.setText("Vehiculo");
        menuregistrarP.add(jMenuItem10);

        menuPreferencial.add(menuregistrarP);

        menuconsultarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/binoculares.png"))); // NOI18N
        menuconsultarP.setText("Consultar");

        consultarempleadosP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado3.png"))); // NOI18N
        consultarempleadosP.setText("Empleados");
        consultarempleadosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarempleadosPActionPerformed(evt);
            }
        });
        menuconsultarP.add(consultarempleadosP);

        consultarvehiculosP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coche.png"))); // NOI18N
        consultarvehiculosP.setText("Vehiculos");
        consultarvehiculosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarvehiculosPActionPerformed(evt);
            }
        });
        menuconsultarP.add(consultarvehiculosP);

        menuPreferencial.add(menuconsultarP);

        jMenuBar2.add(menuPreferencial);

        jMenu11.setText("Ayuda");
        jMenuBar2.add(jMenu11);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctrlUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlUsuariosActionPerformed
                CtrlUsuarios bus = new CtrlUsuarios();
       		bus.setVisible(true);
       		this.dispose();
    }//GEN-LAST:event_ctrlUsuariosActionPerformed

    private void rempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rempleadoActionPerformed
                EmpleadosBuses bus = new EmpleadosBuses();
       		bus.setVisible(true);
       		this.dispose();
    }//GEN-LAST:event_rempleadoActionPerformed

    private void rvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rvehiculoActionPerformed
                VehiculosBuses bus = new VehiculosBuses();
       		bus.setVisible(true);
       		this.dispose();
    }//GEN-LAST:event_rvehiculoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
                EmpleadosTaxis bus = new EmpleadosTaxis();
       		bus.setVisible(true);
       		this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
            
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
                EmpleadosPreferencial bus = new EmpleadosPreferencial();
       		bus.setVisible(true);
       		this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void cempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cempleadoActionPerformed
                TablaBuses bus = new TablaBuses();
       		bus.setVisible(true);
       		
    }//GEN-LAST:event_cempleadoActionPerformed

    private void consultarempleadosTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarempleadosTActionPerformed
                TablaTaxis bus = new TablaTaxis();
       		bus.setVisible(true);
    }//GEN-LAST:event_consultarempleadosTActionPerformed

    private void consultarempleadosPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarempleadosPActionPerformed
                TablaPreferencial bus = new TablaPreferencial();
       		bus.setVisible(true);
    }//GEN-LAST:event_consultarempleadosPActionPerformed

    private void cvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvehiculoActionPerformed
                TablaBusesV bus = new TablaBusesV();
       		bus.setVisible(true);
    }//GEN-LAST:event_cvehiculoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
                TablaTaxisV bus = new TablaTaxisV();
       		bus.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void consultarvehiculosPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarvehiculosPActionPerformed
                TablaPreferencialV bus = new TablaPreferencialV();
       		bus.setVisible(true);
    }//GEN-LAST:event_consultarvehiculosPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cempleado;
    private javax.swing.JMenuItem consultarempleadosP;
    private javax.swing.JMenuItem consultarempleadosT;
    private javax.swing.JMenuItem consultarvehiculosP;
    private javax.swing.JMenuItem ctrlUsuarios;
    private javax.swing.JMenuItem cvehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JMenu menuBuses;
    private javax.swing.JMenu menuPreferencial;
    private javax.swing.JMenu menuTaxis;
    private javax.swing.JMenu menuconsultar;
    private javax.swing.JMenu menuconsultarP;
    private javax.swing.JMenu menuconsultarT;
    private javax.swing.JMenu menuregistrar;
    private javax.swing.JMenu menuregistrarP;
    private javax.swing.JMenu menuregistrarT;
    private javax.swing.JMenuItem rempleado;
    private javax.swing.JMenuItem rvehiculo;
    // End of variables declaration//GEN-END:variables
}
